### PR TITLE
Fix V2, tidy up and make noarch

### PR DESCRIPTION
**Pull request by chrisburr**
Closes #17. I made this noarch as Python 3.5 is not longer supported by conda-forge.

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks, this seems to be working. Is there anything else you want to change or check before we merge it?

**Comment by chrisburr** [comment]
Nope, it's good to go so far as I'm concerned.

**Comment by takluyver** [comment]
OK, great. I don't see anything wrong, but my conda packaging knowledge is limited, so I'll leave it for a little while to give people (e.g. @ocefpaf & @saraedum) a chance to have a look. Otherwise, I'm happy for it to be merged.

**Comment by ocefpaf** [comment]
> but my conda packaging knowledge

So was mine ;-p
You actually stopped exactly where I would have. Thanks @saraedum and @chrisburr for coming to our aid here!

**Pull request merged**
